# .streamlit/secrets.toml

SUPABASE_URL = "https://bzitnpcwmetstczjjpqe.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aXRucGN3bWV0c3RjempqcHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4ODI4NjUsImV4cCI6MjA3OTQ1ODg2NX0.reCq1MJXrTXD9PqowOoYsQSrIxFTAtcDpFJnAPhP2aE"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aXRucGN3bWV0c3RjempqcHFlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2Mzg4Mjg2NSwiZXhwIjoyMDc5NDU4ODY1fQ.BZ4TClzh1im1VOtAxL402yE4QJL8Y2cnvuv9puLhY0k"  # ADD THIS


# Email Configuration - Gmail
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SENDER_EMAIL = "arunav.jsr.0604@gmail.com"
SENDER_PASSWORD = "rhdm pufr otuk crns"  
SENDER_NAME = "HR Team"
COMPANY_NAME = "Your Pvt Ltd"
OPENAI_API_KEY = "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"